version: "3.9"
services:
  pocketbase:
    image: ghcr.io/pocketbase/pocketbase:latest
    command: ["serve", "--http=0.0.0.0:8090", "--dir=/pb_data"]
    volumes:
      - pb_data:/pb_data
    ports:
      - "8090:8090"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      VITE_API_BASE: http://localhost:8090
    ports:
      - "3000:80"
volumes:
  pb_data:
