services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pb
      # Optionally pin a version on build:
      # args:
      #   PB_VERSION: "0.31.0"
    command: ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080", "--dir=/pb/pb_data"]
    volumes:
      - pb_data:/pb/pb_data
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      # Your Vite app reads this to talk to PocketBase
      VITE_API_BASE: http://localhost:8080
    ports:
      - "3003:80"
    depends_on:
      - pocketbase

volumes:
  pb_data:
